rust/doc : add rust building
alipay/fury pull request #1129
Opened 2023-11-22 03:26 UTC by caicancai

## What do these changes do?

## Related issue number

Closes #xxxx

## Check code requirements

- [ ] tests added / passed (if needed)
- [ ] Ensure all linting tests pass, see [here](https://github.com/alipay/fury/blob/main/CONTRIBUTING.rst) for how to run them

2023-11-22 03:29 UTC, caicancai commented
The DEVELOPMENT.md layout seems a little ugly, I will re-optimize it later

2023-11-22 03:40 UTC, chaokunyang commented
@wangweipeng2 Could you help review this?

2023-11-22 11:29 UTC, wangweipeng2 commented on docs/guide/DEVELOPMENT.md
> +rust build
Rust usually uses Cargo to build and test, is this a typo?

2023-11-23 03:08 UTC, wangweipeng2 approved these changes
LGTM

2023-11-23 03:16 UTC, wangweipeng2 requested changes
@caicancai  "cd rust' is ok. The root directory is a cargo workspace, and cargo would automatically lookup the members."

2023-11-23 03:19 UTC, caicancai commented
<img width="541" alt="a15a906b6bb1e373bca3f5625e2292f" src="https://github.com/alipay/fury/assets/77189278/41bd2389-284c-405f-bc25-2cef80fdd57d">

cd rust, and then execute cargo test will give an error

2023-11-23 06:31 UTC, wangweipeng2 commented
> <img alt="a15a906b6bb1e373bca3f5625e2292f" width="541" src="https://user-images.githubusercontent.com/77189278/285092302-41bd2389-284c-405f-bc25-2cef80fdd57d.png">
> cd rust, and then execute cargo test will give an error. cd rust/fury will not report an error. cc @chaokunyang
@caicancai 
It should have been caused by my incorrect code the day before yesterday, so the error report is reasonable. I will fix it.

2023-11-23 06:31 UTC, wangweipeng2 approved these changes
LGTM

2023-11-23 06:32 UTC, merged

2023-11-23 07:13 UTC, chaokunyang commented
> <img alt="a15a906b6bb1e373bca3f5625e2292f" width="541" src="https://user-images.githubusercontent.com/77189278/285092302-41bd2389-284c-405f-bc25-2cef80fdd57d.png">
> cd rust, and then execute cargo test will give an error. cd rust/fury will not report an error. cc @chaokunyang

Good catch, thanks for this, @caicancai